version: '3.9'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crafts
      MYSQL_USER: crafts
      MYSQL_PASSWORD: crafts 
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./DB.sql:/docker-entrypoint-initdb.d/init.sql

  api-spring-boot:
    build: ./
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/crafts
      - DB_USERNAME=crafts
      - DB_PASSWORD=crafts
    ports:
      - 8080:8080
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
