version: '3.9'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crafts
      MYSQL_USER: crafts
      MYSQL_PASSWORD: crafts 
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

